# Generated by Django 6.0.6 on 2026-06-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_us', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
